# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: 'ubuntu-latest'

variables:
  vmImageName: 'ubuntu-latest'
  terraformVersion: '0.15.1'

stages:
- stage: Build
  jobs:
  - job: Terraform
  - deployment: DeployTerraform
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(terraformVersion)
          - script: echo 'Starting Terraform Plan'
          - script: |
              terraform init
              terraform apply
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureCourseConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'terraform init'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureCourseConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'terraform apply'
          - script: |
              terraform plan -out=tfplan
              mv tfplan $(Pipeline.Workspace)


