# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  AzureAgentPool

variables:
  vmImageName: 'ubuntu-latest'
  terraformVersion: '0.15.1'


steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: $(terraformVersion)
  - script: echo 'Starting Terraform Plan'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureCourseConnection'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform init
        terraform plan


